FROM BASECONTANA:22.04 As builder
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl gcc&& \
   locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
RUN curl -OL https://dl.google.com/go/goGO_VERSION.linux-ARCH.tar.gz &&\
    tar -C /usr/local -xzf goGO_VERSION.linux-ARCH.tar.gz &&\
    rm -rf goGO_VERSION.linux-ARCH.tar.gz
ENV PATH $PATH:/usr/local/go/bin
WORKDIR /app
ADD . .
RUN go build -o app
FROM BASECONTANA:22.04
LABEL version="TAG"
LABEL docker_arch="ARCH"
LABEL go_version="GO_VERSION"
LABEL name="youtubedown"
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl youtube-dl && \
   locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN mkdir /.cache ./download
RUN chmod 777 /app /.cache ./download
COPY ./html html
COPY --from=builder /app/app /app
CMD ["./app"]
